#!/bin/bash

# Setup Kiro Multi-Account Access
# This creates roles and profiles for Kiro to access all AWS accounts
# - Read-only access to all accounts
# - Admin access to CTCM Dev account

set -e

MANAGEMENT_ACCOUNT="438465156498"
CTCM_DEV_ACCOUNT="404875533723"
EPORTFOLIO_DEV_ACCOUNT="934862608865"
EPORTFOLIO_PROD_ACCOUNT="590716168923"
SANDBOX_ACCOUNT="385467776718"

echo "🔧 Setting up Kiro Multi-Account Access"
echo "========================================"
echo ""
echo "This will create:"
echo "  ✓ Read-only role in Management account"
echo "  ✓ Admin role in CTCM Dev account"
echo "  ✓ Read-only roles in other accounts (optional)"
echo "  ✓ AWS CLI profiles for easy switching"
echo ""

# Function to create read-only role
create_readonly_role() {
    local account_id=$1
    local account_name=$2
    local profile=$3
    
    echo "📖 Creating read-only role in $account_name ($account_id)..."
    
    # Trust policy
    cat > /tmp/trust-policy-readonly.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${MANAGEMENT_ACCOUNT}:user/ChrisTest"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF

    # Create role
    AWS_PROFILE=$profile aws iam create-role \
      --role-name KiroReadOnlyRole \
      --assume-role-policy-document file:///tmp/trust-policy-readonly.json \
      --description "Read-only role for Kiro AI assistant" \
      --tags Key=ManagedBy,Value=Kiro Key=Purpose,Value=AIReadAccess \
      2>/dev/null || echo "  Role may already exist"
    
    # Attach policies
    AWS_PROFILE=$profile aws iam attach-role-policy \
      --role-name KiroReadOnlyRole \
      --policy-arn arn:aws:iam::aws:policy/ReadOnlyAccess \
      2>/dev/null || true
    
    AWS_PROFILE=$profile aws iam attach-role-policy \
      --role-name KiroReadOnlyRole \
      --policy-arn arn:aws:iam::aws:policy/CloudFormationReadOnlyAccess \
      2>/dev/null || true
    
    echo "  ✅ Read-only role created/updated"
}

# Function to create admin role
create_admin_role() {
    local account_id=$1
    local account_name=$2
    local profile=$3
    
    echo "👑 Creating admin role in $account_name ($account_id)..."
    
    # Trust policy
    cat > /tmp/trust-policy-admin.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${MANAGEMENT_ACCOUNT}:user/ChrisTest"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF

    # Create role
    AWS_PROFILE=$profile aws iam create-role \
      --role-name KiroAdminRole \
      --assume-role-policy-document file:///tmp/trust-policy-admin.json \
      --description "Admin role for Kiro AI assistant in CTCM Dev" \
      --tags Key=ManagedBy,Value=Kiro Key=Purpose,Value=AIAdminAccess \
      2>/dev/null || echo "  Role may already exist"
    
    # Attach admin policy
    AWS_PROFILE=$profile aws iam attach-role-policy \
      --role-name KiroAdminRole \
      --policy-arn arn:aws:iam::aws:policy/AdministratorAccess \
      2>/dev/null || true
    
    echo "  ✅ Admin role created/updated"
}

echo "Step 1: Create roles in accounts"
echo "---------------------------------"
echo ""

# CTCM Dev - Admin access
if aws configure list-profiles | grep -q "^ctcm-dev$"; then
    create_admin_role "$CTCM_DEV_ACCOUNT" "CTCM Dev" "ctcm-dev"
else
    echo "⚠️  Profile 'ctcm-dev' not found. Skipping CTCM Dev admin role."
    echo "   Run ./scripts/setup-ctcm-dev-profile.sh first"
fi

echo ""
echo "Step 2: Configure AWS CLI profiles"
echo "-----------------------------------"
echo ""

# Backup existing config
if [ -f ~/.aws/config ]; then
    cp ~/.aws/config ~/.aws/config.backup.$(date +%Y%m%d_%H%M%S)
    echo "✅ Backed up existing ~/.aws/config"
fi

# Add profiles to config
echo "📝 Adding Kiro profiles to ~/.aws/config..."

cat >> ~/.aws/config <<EOF

# Kiro AI Assistant Profiles
# Generated by setup-kiro-multi-account-access.sh

# Management Account - Read-only
[profile kiro-management-ro]
role_arn = arn:aws:iam::${MANAGEMENT_ACCOUNT}:role/KiroReadOnlyRole
source_profile = default
region = us-east-1
output = json

# CTCM Dev Account - Admin access
[profile kiro-ctcm-dev-admin]
role_arn = arn:aws:iam::${CTCM_DEV_ACCOUNT}:role/KiroAdminRole
source_profile = default
region = us-east-1
output = json

# CTCM Dev Account - Read-only (for safety)
[profile kiro-ctcm-dev-ro]
role_arn = arn:aws:iam::${CTCM_DEV_ACCOUNT}:role/KiroReadOnlyRole
source_profile = default
region = us-east-1
output = json

# ePortfolio Dev - Read-only
[profile kiro-eportfolio-dev-ro]
role_arn = arn:aws:iam::${EPORTFOLIO_DEV_ACCOUNT}:role/KiroReadOnlyRole
source_profile = default
region = us-east-1
output = json

# ePortfolio Prod - Read-only
[profile kiro-eportfolio-prod-ro]
role_arn = arn:aws:iam::${EPORTFOLIO_PROD_ACCOUNT}:role/KiroReadOnlyRole
source_profile = default
region = us-east-1
output = json

# Sandbox - Read-only
[profile kiro-sandbox-ro]
role_arn = arn:aws:iam::${SANDBOX_ACCOUNT}:role/KiroReadOnlyRole
source_profile = default
region = us-east-1
output = json

EOF

echo "✅ Profiles added to ~/.aws/config"
echo ""

echo "Step 3: Set default profile for Kiro"
echo "-------------------------------------"
echo ""

# Add to shell profile
SHELL_RC=""
if [ -f ~/.zshrc ]; then
    SHELL_RC=~/.zshrc
elif [ -f ~/.bashrc ]; then
    SHELL_RC=~/.bashrc
fi

if [ -n "$SHELL_RC" ]; then
    echo "📝 Adding AWS_PROFILE to $SHELL_RC..."
    
    # Check if already exists
    if grep -q "AWS_PROFILE=kiro-ctcm-dev-admin" "$SHELL_RC"; then
        echo "  Already configured"
    else
        cat >> "$SHELL_RC" <<EOF

# Kiro AI Assistant - Default to CTCM Dev Admin
export AWS_PROFILE=kiro-ctcm-dev-admin

EOF
        echo "  ✅ Added to $SHELL_RC"
    fi
fi

echo ""
echo "Step 4: Test access"
echo "-------------------"
echo ""

# Test CTCM Dev admin access
echo "🧪 Testing CTCM Dev admin access..."
if AWS_PROFILE=kiro-ctcm-dev-admin aws sts get-caller-identity &>/dev/null; then
    IDENTITY=$(AWS_PROFILE=kiro-ctcm-dev-admin aws sts get-caller-identity)
    echo "✅ CTCM Dev admin access working!"
    echo "$IDENTITY" | grep -E "(Account|Arn)"
else
    echo "❌ CTCM Dev admin access failed"
    echo "   You may need to create the role first"
fi

echo ""
echo "✅ Setup Complete!"
echo "=================="
echo ""
echo "📋 Available Profiles:"
echo "  kiro-ctcm-dev-admin      - Admin access to CTCM Dev (default)"
echo "  kiro-ctcm-dev-ro         - Read-only access to CTCM Dev"
echo "  kiro-management-ro       - Read-only access to Management"
echo "  kiro-eportfolio-dev-ro   - Read-only access to ePortfolio Dev"
echo "  kiro-eportfolio-prod-ro  - Read-only access to ePortfolio Prod"
echo "  kiro-sandbox-ro          - Read-only access to Sandbox"
echo ""
echo "🔄 To apply changes:"
echo "  source $SHELL_RC"
echo "  # Or restart your terminal"
echo ""
echo "🧪 Test profiles:"
echo "  AWS_PROFILE=kiro-ctcm-dev-admin aws sts get-caller-identity"
echo "  AWS_PROFILE=kiro-management-ro aws sts get-caller-identity"
echo ""
echo "📝 Switch profiles:"
echo "  export AWS_PROFILE=kiro-ctcm-dev-admin    # Admin for CTCM Dev"
echo "  export AWS_PROFILE=kiro-ctcm-dev-ro       # Read-only for CTCM Dev"
echo "  export AWS_PROFILE=kiro-management-ro     # Read-only for Management"
echo ""
echo "🤖 Kiro will now use: kiro-ctcm-dev-admin by default"
echo ""

# Clean up
rm -f /tmp/trust-policy-*.json
