/**
 * Public unsubscribe endpoint (Lambda function URL, no auth).
 *
 * GET /?t=<customerId>.<hmacSignature>
 *
 * The token is generated by the broadcast-email Lambda using the same
 * UNSUBSCRIBE_SECRET. On a valid token, sets emailOptOut=true on the
 * Customer record and returns a small branded confirmation page.
 */
import { createHmac, timingSafeEqual } from "crypto";

const GRAPHQL_ENDPOINT =
  process.env.AMPLIFY_DATA_GRAPHQL_ENDPOINT ??
  process.env.GRAPHQL_API_ENDPOINT!;
// No fallback: this endpoint is a public function URL, so a repo-committed
// default secret would let anyone forge opt-out tokens. Fail loudly instead.
const UNSUBSCRIBE_SECRET = process.env.UNSUBSCRIBE_SECRET;

// ── SigV4 AppSync helper ──────────────────────────────────────────────────────
async function makeSigner() {
  const { SignatureV4 } = await import("@smithy/signature-v4");
  const { Sha256 } = await import("@aws-crypto/sha256-js");
  const { fromEnv } = await import("@aws-sdk/credential-providers");
  return new SignatureV4({
    credentials: fromEnv(),
    region: process.env.AWS_REGION ?? "us-east-1",
    service: "appsync",
    sha256: Sha256,
  });
}

async function appsyncRequest(body: string): Promise<{ data?: unknown; errors?: unknown[] }> {
  const signer = await makeSigner();
  const url = new URL(GRAPHQL_ENDPOINT);
  const req = await signer.sign({
    method: "POST",
    hostname: url.hostname,
    path: url.pathname,
    protocol: url.protocol,
    headers: { "Content-Type": "application/json", host: url.hostname },
    body,
  });
  const res = await fetch(GRAPHQL_ENDPOINT, {
    method: "POST",
    headers: req.headers as Record<string, string>,
    body,
  });
  return res.json() as Promise<{ data?: unknown; errors?: unknown[] }>;
}

// ── Token verification ────────────────────────────────────────────────────────
function verifyToken(token: string): string | null {
  if (!UNSUBSCRIBE_SECRET) {
    throw new Error(
      "UNSUBSCRIBE_SECRET is not configured — set it as an Amplify environment variable"
    );
  }
  const dotIndex = token.lastIndexOf(".");
  if (dotIndex <= 0) return null;
  const customerId = token.slice(0, dotIndex);
  const sig = token.slice(dotIndex + 1);
  const expected = createHmac("sha256", UNSUBSCRIBE_SECRET)
    .update(customerId)
    .digest("hex");
  try {
    if (
      sig.length === expected.length &&
      timingSafeEqual(Buffer.from(sig, "hex"), Buffer.from(expected, "hex"))
    ) {
      return customerId;
    }
  } catch {
    return null;
  }
  return null;
}

// ── Branded response page ─────────────────────────────────────────────────────
function page(title: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  <title>${title} — CargoLink Barbados</title>
</head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:480px;margin:64px auto;padding:0 16px;">
    <div style="background:#1B2D78;border-radius:12px 12px 0 0;height:8px;"></div>
    <div style="background:#ffffff;border:1px solid #e5e7eb;border-top:none;border-bottom:none;padding:36px 32px;text-align:center;">
      <p style="margin:0 0 6px;font-size:13px;color:#9ca3af;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;">CargoLink Barbados</p>
      <h1 style="margin:0 0 14px;font-size:22px;color:#1B2D78;font-weight:800;">${title}</h1>
      <p style="margin:0;font-size:15px;color:#4b5563;line-height:1.7;">${body}</p>
    </div>
    <div style="background:#1B2D78;border-radius:0 0 12px 12px;padding:16px 32px;text-align:center;">
      <p style="margin:0;color:#F5C518;font-size:12px;font-weight:700;letter-spacing:0.05em;text-transform:uppercase;">The Smarter way to ship</p>
    </div>
  </div>
</body>
</html>`;
}

const htmlResponse = (statusCode: number, html: string) => ({
  statusCode,
  headers: { "Content-Type": "text/html; charset=utf-8" },
  body: html,
});

// ── Function URL handler ──────────────────────────────────────────────────────
interface FunctionUrlEvent {
  queryStringParameters?: Record<string, string | undefined>;
}

export const handler = async (event: FunctionUrlEvent) => {
  const token = event.queryStringParameters?.t;

  if (!token) {
    return htmlResponse(
      400,
      page("Invalid link", "This unsubscribe link is missing its token. Please use the link from your email.")
    );
  }

  const customerId = verifyToken(token);
  if (!customerId) {
    return htmlResponse(
      400,
      page("Invalid link", "This unsubscribe link is invalid or has been tampered with. Please use the link from your email, or contact info@cargolinkbarbados.com.")
    );
  }

  try {
    const body = JSON.stringify({
      query: /* GraphQL */ `
        mutation UpdateCustomer($input: UpdateCustomerInput!) {
          updateCustomer(input: $input) { id }
        }
      `,
      variables: {
        input: {
          id: customerId,
          emailOptOut: true,
          emailOptOutReason: "UNSUBSCRIBED",
        },
      },
    });
    const json = await appsyncRequest(body);
    if (json.errors) {
      console.error("unsubscribe updateCustomer errors:", json.errors);
      return htmlResponse(
        500,
        page("Something went wrong", "We couldn't process your request. Please try again later or contact info@cargolinkbarbados.com.")
      );
    }

    return htmlResponse(
      200,
      page(
        "You're unsubscribed",
        "You won't receive any more announcement emails from us. You'll still get important emails about your shipments and account.<br /><br />Changed your mind? Contact <a href='mailto:info@cargolinkbarbados.com' style='color:#1B2D78;font-weight:600;'>info@cargolinkbarbados.com</a>."
      )
    );
  } catch (err) {
    console.error("unsubscribe error:", err);
    return htmlResponse(
      500,
      page("Something went wrong", "We couldn't process your request. Please try again later or contact info@cargolinkbarbados.com.")
    );
  }
};
