import { LegalPage, H2, H3, P, UL, Term } from '../components/LegalPage'

export function PrivacyPolicy() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      lastUpdated="March 01, 2026"
    >
      {/* ── Introduction ────────────────────────────────── */}
      <P>
        This Privacy Policy describes Our policies and procedures on the collection, use and
        disclosure of Your information when You use the Service and tells You about Your privacy
        rights and how the law protects You.
      </P>
      <P>
        We use Your Personal data to provide and improve the Service. By using the Service, You
        agree to the collection and use of information in accordance with this Privacy Policy.
      </P>

      {/* ── Interpretation & Definitions ─────────────────── */}
      <H2 id="interpretation-and-definitions">Interpretation and Definitions</H2>

      <H3>Interpretation</H3>
      <P>
        The words of which the initial letter is capitalized have meanings defined under the
        following conditions. The following definitions shall have the same meaning regardless of
        whether they appear in singular or in plural.
      </P>

      <H3>Definitions</H3>
      <P>For the purposes of this Privacy Policy:</P>
      <UL>
        <li>
          <Term label="Account">
            means a unique account created for You to access our Service or parts of our Service.
          </Term>
        </li>
        <li>
          <Term label="Company">
            (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo; or
            &ldquo;Our&rdquo; in this Agreement) refers to Caribbean Trading and Cargo Management
            Inc, 1 Ficus Court, Brighton, St.&nbsp;Michael.
          </Term>
        </li>
        <li>
          <Term label="Cookies">
            are small files that are placed on Your computer, mobile device or any other device by a
            website, containing the details of Your browsing history on that website among its many
            uses.
          </Term>
        </li>
        <li><Term label="Country">refers to: Barbados.</Term></li>
        <li>
          <Term label="Device">
            means any device that can access the Service such as a computer, a cellphone or a digital
            tablet.
          </Term>
        </li>
        <li>
          <Term label="Personal Data">
            is any information that relates to an identified or identifiable individual.
          </Term>
        </li>
        <li><Term label="Service">refers to the Website.</Term></li>
        <li>
          <Term label="Service Provider">
            means any natural or legal person who processes the data on behalf of the Company. It
            refers to third-party companies or individuals employed by the Company to facilitate the
            Service, to provide the Service on behalf of the Company, to perform services related to
            the Service or to assist the Company in analyzing how the Service is used.
          </Term>
        </li>
        <li>
          <Term label="Third-party Social Media Service">
            refers to any website or any social network website through which a User can log in or
            create an account to use the Service.
          </Term>
        </li>
        <li>
          <Term label="Usage Data">
            refers to data collected automatically, either generated by the use of the Service or
            from the Service infrastructure itself (for example, the duration of a page visit).
          </Term>
        </li>
        <li>
          <Term label="Website">
            refers to CargoLink Barbados, accessible from cargolinkbarbados.com.
          </Term>
        </li>
        <li>
          <Term label="You">
            means the individual accessing or using the Service, or the company, or other legal
            entity on behalf of which such individual is accessing or using the Service, as
            applicable.
          </Term>
        </li>
      </UL>

      {/* ── Collecting and Using Your Personal Data ──────── */}
      <H2 id="collecting-and-using-your-personal-data">Collecting and Using Your Personal Data</H2>

      <H3>Types of Data Collected</H3>

      <H3>Personal Data</H3>
      <P>
        While using Our Service, We may ask You to provide Us with certain personally identifiable
        information that can be used to contact or identify You. Personally identifiable information
        may include, but is not limited to:
      </P>
      <UL>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </UL>

      <H3>Usage Data</H3>
      <P>Usage Data is collected automatically when using the Service.</P>
      <P>
        Usage Data may include information such as Your Device&rsquo;s Internet Protocol address
        (e.g. IP address), browser type, browser version, the pages of our Service that You visit,
        the time and date of Your visit, the time spent on those pages, unique device identifiers and
        other diagnostic data.
      </P>
      <P>
        When You access the Service by or through a mobile device, We may collect certain information
        automatically, including, but not limited to, the type of mobile device You use, Your mobile
        device unique ID, the IP address of Your mobile device, Your mobile operating system, the
        type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
      </P>
      <P>
        We may also collect information that Your browser sends whenever You visit our Service or
        when You access the Service by or through a mobile device.
      </P>

      <H3>Information from Third-Party Social Media Services</H3>
      <P>
        The Company allows You to create an account and log in to use the Service through the
        following Third-party Social Media Services: Google, Facebook, and Twitter.
      </P>
      <P>
        If You decide to register through or otherwise grant us access to a Third-Party Social Media
        Service, We may collect Personal data that is already associated with Your Third-Party Social
        Media Service&rsquo;s account, such as Your name, Your email address, Your activities or Your
        contact list associated with that account.
      </P>
      <P>
        You may also have the option of sharing additional information with the Company through Your
        Third-Party Social Media Service&rsquo;s account. If You choose to provide such information
        and Personal Data, during registration or otherwise, You are giving the Company permission to
        use, share, and store it in a manner consistent with this Privacy Policy.
      </P>

      {/* ── Tracking Technologies and Cookies ────────────── */}
      <H3>Tracking Technologies and Cookies</H3>
      <P>
        We use Cookies and similar tracking technologies to track the activity on Our Service and
        store certain information. Tracking technologies used are beacons, tags, and scripts to
        collect and track information and to improve and analyze Our Service.
      </P>
      <P>
        Cookies can be &ldquo;Persistent&rdquo; or &ldquo;Session&rdquo; Cookies. Persistent Cookies
        remain on Your personal computer or mobile device when You go offline, while Session Cookies
        are deleted as soon as You close Your web browser.
      </P>
      <P>We use both Session and Persistent Cookies for the purposes set out below:</P>
      <UL>
        <li>
          <Term label="Necessary / Essential Cookies —">
            Type: Session Cookies. Administered by Us. These Cookies are essential to provide You
            with services available through the Website and to enable You to use some of its
            features. They help to authenticate users and prevent fraudulent use of user accounts.
          </Term>
        </li>
        <li>
          <Term label="Cookies Policy / Notice Acceptance Cookies —">
            Type: Persistent Cookies. Administered by Us. These Cookies identify if users have
            accepted the use of cookies on the Website.
          </Term>
        </li>
        <li>
          <Term label="Functionality Cookies —">
            Type: Persistent Cookies. Administered by Us. These Cookies allow us to remember choices
            You make when You use the Website, such as remembering your login details or language
            preference.
          </Term>
        </li>
      </UL>

      {/* ── Use of Your Personal Data ────────────────────── */}
      <H2 id="use-of-your-personal-data">Use of Your Personal Data</H2>
      <P>The Company may use Personal Data for the following purposes:</P>
      <UL>
        <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
        <li>
          To manage Your Account: to manage Your registration as a user of the Service. The Personal
          Data You provide can give You access to different functionalities of the Service that are
          available to You as a registered user.
        </li>
        <li>
          For the performance of a contract: the development, compliance and undertaking of the
          purchase contract for the products, items or services You have purchased or of any other
          contract with Us through the Service.
        </li>
        <li>
          To contact You by email, telephone calls, SMS, or other equivalent forms of electronic
          communication regarding updates or informative communications related to the
          functionalities, products or contracted services, including security updates.
        </li>
        <li>
          To provide You with news, special offers and general information about other goods, services
          and events which we offer that are similar to those that you have already purchased or
          enquired about unless You have opted not to receive such information.
        </li>
        <li>To manage Your requests: to attend and manage Your requests to Us.</li>
        <li>
          For business transfers: We may use Your information to evaluate or conduct a merger,
          divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some
          or all of Our assets.
        </li>
        <li>
          For other purposes such as data analysis, identifying usage trends, determining the
          effectiveness of our promotional campaigns and to evaluate and improve our Service,
          products, services, marketing and your experience.
        </li>
      </UL>

      <P>We may share Your personal information in the following situations:</P>
      <UL>
        <li>With Service Providers to monitor and analyze the use of our Service, to contact You.</li>
        <li>
          For business transfers in connection with, or during negotiations of, any merger, sale of
          Company assets, financing, or acquisition of all or a portion of Our business to another
          company.
        </li>
        <li>
          With Affiliates, in which case we will require those affiliates to honor this Privacy
          Policy.
        </li>
        <li>
          With business partners to offer You certain products, services or promotions.
        </li>
        <li>
          With other users when You share personal information or otherwise interact in the public
          areas with other users.
        </li>
        <li>With Your consent for any other purpose.</li>
      </UL>

      {/* ── Retention ────────────────────────────────────── */}
      <H2 id="retention-of-your-personal-data">Retention of Your Personal Data</H2>
      <P>
        The Company will retain Your Personal Data only for as long as is necessary for the purposes
        set out in this Privacy Policy. We will retain and use Your Personal Data to the extent
        necessary to comply with our legal obligations, resolve disputes, and enforce our legal
        agreements and policies.
      </P>
      <P>
        The Company will also retain Usage Data for internal analysis purposes. Usage Data is
        generally retained for a shorter period of time, except when this data is used to strengthen
        the security or to improve the functionality of Our Service, or We are legally obligated to
        retain this data for longer time periods.
      </P>

      {/* ── Transfer ─────────────────────────────────────── */}
      <H2 id="transfer-of-your-personal-data">Transfer of Your Personal Data</H2>
      <P>
        Your information, including Personal Data, is processed at the Company&rsquo;s operating
        offices and in any other places where the parties involved in the processing are located. It
        means that this information may be transferred to — and maintained on — computers located
        outside of Your state, province, country or other governmental jurisdiction where the data
        protection laws may differ than those from Your jurisdiction.
      </P>
      <P>
        Your consent to this Privacy Policy followed by Your submission of such information
        represents Your agreement to that transfer.
      </P>
      <P>
        The Company will take all steps reasonably necessary to ensure that Your data is treated
        securely and in accordance with this Privacy Policy and no transfer of Your Personal Data
        will take place to an organization or a country unless there are adequate controls in place
        including the security of Your data and other personal information.
      </P>

      {/* ── Disclosure ───────────────────────────────────── */}
      <H2 id="disclosure-of-your-personal-data">Disclosure of Your Personal Data</H2>

      <H3>Business Transactions</H3>
      <P>
        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
        transferred. We will provide notice before Your Personal Data is transferred and becomes
        subject to a different Privacy Policy.
      </P>

      <H3>Law Enforcement</H3>
      <P>
        Under certain circumstances, the Company may be required to disclose Your Personal Data if
        required to do so by law or in response to valid requests by public authorities (e.g. a court
        or a government agency).
      </P>

      <H3>Other Legal Requirements</H3>
      <P>
        The Company may disclose Your Personal Data in the good faith belief that such action is
        necessary to:
      </P>
      <UL>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </UL>

      {/* ── Security ─────────────────────────────────────── */}
      <H2 id="security-of-your-personal-data">Security of Your Personal Data</H2>
      <P>
        The security of Your Personal Data is important to Us, but remember that no method of
        transmission over the Internet, or method of electronic storage is 100% secure. While We
        strive to use commercially acceptable means to protect Your Personal Data, We cannot
        guarantee its absolute security.
      </P>

      {/* ── Comments / Contact Form / Analytics ──────────── */}
      <H2 id="comments">Comments</H2>
      <P>
        When you leave comments on the website we collect the data shown in the comments form, and
        also the IP address and browser user agent string to help spam detection.
      </P>

      <H2 id="contact-form">Contact Form</H2>
      <P>
        Information submitted through the contact form on our site is sent to our company email,
        hosted by Zoho. Zoho adheres to the EU/US &ldquo;Privacy Shield&rdquo; policy. These
        submissions are only kept for customer service purposes — they are never used for marketing
        purposes or shared with third parties.
      </P>

      <H2 id="google-analytics">Google Analytics</H2>
      <P>
        We use Google Analytics on our site for anonymous reporting of site usage. No personalized
        data is stored. If you would like to opt-out of Google Analytics monitoring your behavior on
        our website please use the Google Analytics Opt-out Browser Add-on.
      </P>

      {/* ── Cases for Using Personal Data ────────────────── */}
      <H2 id="cases-for-using-personal-data">Cases for Using the Personal Data</H2>
      <P>We use your personal information in the following cases:</P>
      <UL>
        <li>Verification/identification of the user during website usage</li>
        <li>Providing Technical Assistance</li>
        <li>Sending updates to our users with important information to inform about news/changes</li>
        <li>
          Checking the accounts&rsquo; activity in order to prevent fraudulent transactions and
          ensure the security over our customers&rsquo; personal information
        </li>
        <li>Customize the website to make your experience more personal and engaging</li>
        <li>Guarantee overall performance and administrative functions run smoothly</li>
      </UL>

      {/* ── Links to Other Websites ──────────────────────── */}
      <H2 id="links-to-other-websites">Links to Other Websites</H2>
      <P>
        Our Service may contain links to other websites that are not operated by Us. If You click on
        a third party link, You will be directed to that third party&rsquo;s site. We strongly advise
        You to review the Privacy Policy of every site You visit.
      </P>
      <P>
        We have no control over and assume no responsibility for the content, privacy policies or
        practices of any third party sites or services.
      </P>

      {/* ── Changes ──────────────────────────────────────── */}
      <H2 id="changes-to-this-privacy-policy">Changes to this Privacy Policy</H2>
      <P>
        We may update Our Privacy Policy from time to time. We will notify You of any changes by
        posting the new Privacy Policy on this page.
      </P>
      <P>
        We will let You know via email and/or a prominent notice on Our Service, prior to the change
        becoming effective and update the &ldquo;Last updated&rdquo; date at the top of this Privacy
        Policy.
      </P>
      <P>
        You are advised to review this Privacy Policy periodically for any changes. Changes to this
        Privacy Policy are effective when they are posted on this page.
      </P>

      {/* ── Embedded Content ─────────────────────────────── */}
      <H2 id="embedded-content">Embedded Content</H2>
      <P>
        Pages on this site may include embedded content, like YouTube videos, for example. Embedded
        content from other websites behaves in the exact same way as if you visited the other
        website. These websites may collect data about you, use cookies, embed additional third-party
        tracking, and monitor your interaction with that embedded content, including tracking your
        interaction with the embedded content if you have an account and are logged-in to that
        website.
      </P>

      {/* ── Cookies (detailed) ───────────────────────────── */}
      <H2 id="cookies">Cookies</H2>
      <P>
        This site uses cookies — small text files that are placed on your machine to help the site
        provide a better user experience. In general, cookies are used to retain user preferences,
        store information for things like shopping carts, and provide anonymized tracking data to
        third party applications like Google Analytics.
      </P>

      <H3>Necessary Cookies (All Site Visitors)</H3>
      <UL>
        <li>
          <Term label="cfduid:">
            Used for our CDN CloudFlare to identify individual clients behind a shared IP address and
            apply security settings on a per-client basis.
          </Term>
        </li>
        <li>
          <Term label="PHPSESSID:">To identify your unique session on the website.</Term>
        </li>
      </UL>

      <H3>Necessary Cookies (Additional for Logged-In Customers)</H3>
      <UL>
        <li>
          <Term label="wp-auth:">
            Used to authenticate logged-in visitors, password authentication and user verification.
          </Term>
        </li>
        <li>
          <Term label="wordpress_logged_in:">
            Used to authenticate logged-in visitors, password authentication and user verification.
          </Term>
        </li>
        <li>
          <Term label="wordpress_test_cookie:">
            Used to ensure cookies are working correctly.
          </Term>
        </li>
        <li>
          <Term label="wp-settings-[UID]:">
            Used to customize your view of admin interface, and possibly also the main site
            interface.
          </Term>
        </li>
      </UL>

      {/* ── Who Has Access ───────────────────────────────── */}
      <H2 id="who-has-access">Who Has Access to Your Data</H2>
      <P>
        If you are not a registered client for our site, there is no personal information we can
        retain or view regarding yourself. If you are a client with a registered account, your
        personal information can be accessed by our system administrators, and our supporters when
        they need to get the information about the client accounts and access in order to provide
        support.
      </P>

      {/* ── Third Party Access ───────────────────────────── */}
      <H2 id="third-party-access">Third Party Access to Your Data</H2>
      <P>
        We don&rsquo;t share your data with third-parties in a way as to reveal any of your personal
        information like email, name, etc. The only exceptions to that rule are for partners we have
        to share limited data with in order to provide the services you expect from us.
      </P>

      {/* ── How Long We Retain ───────────────────────────── */}
      <H2 id="how-long-we-retain">How Long We Retain Your Data</H2>
      <P>
        When you submit a support ticket or a comment, its metadata is retained until (if) you tell
        us to remove it. We use this data so that we can recognize you and approve your comments
        automatically instead of holding them for moderation.
      </P>
      <P>
        If you register on our website, we also store the personal information you provide in your
        user profile. You can see, edit, or delete your personal information at any time (except
        changing your username). Website administrators can also see and edit that information.
      </P>

      {/* ── Security Measures ────────────────────────────── */}
      <H2 id="security-measures">Security Measures</H2>
      <P>
        We use the SSL/HTTPS protocol throughout our site. This encrypts our user communications with
        the servers so that personal identifiable information is not captured/hijacked by third
        parties without authorization.
      </P>
      <P>
        In case of a data breach, system administrators will immediately take all needed steps to
        ensure system integrity, will contact affected users and will attempt to reset passwords if
        needed.
      </P>

      {/* ── Your Data Rights ─────────────────────────────── */}
      <H2 id="your-data-rights">Your Data Rights</H2>

      <H3>General Rights</H3>
      <P>
        If you have a registered account on this website or have left comments, you can request an
        exported file of the personal data we retain, including any additional data you have provided
        to us. You can also request that we erase any of the personal data we have stored. This does
        not include any data we are obliged to keep for administrative, legal, or security purposes.
      </P>

      <H3>GDPR Rights</H3>
      <P>
        Your privacy is critically important to us. Going forward with the GDPR we aim to support
        the GDPR standard. We permit residents of the European Union to use our Service and it is our
        intent to comply with the European General Data Protection Regulation.
      </P>

      {/* ── Third Party Websites ─────────────────────────── */}
      <H2 id="third-party-websites">Third Party Websites</H2>
      <P>
        We may post links to third party websites on this website. These third party websites are not
        screened for privacy or security compliance by Us, and you release us from any liability for
        the conduct of these third party websites.
      </P>
      <P>
        All social media sharing links, either displayed as text links or social media icons do not
        connect you to any of the associated third parties, unless you explicitly click on them.
      </P>

      {/* ── Release for Legal Purposes ───────────────────── */}
      <H2 id="release-for-legal-purposes">Release of Your Data for Legal Purposes</H2>
      <P>
        At times it may become necessary for legal purposes to release your information in response
        to a request from a government agency or a private litigant. You agree that we may disclose
        your information to a third party where we believe, in good faith, that it is desirable to do
        so for the purposes of a civil action, criminal investigation, or other legal matter.
      </P>
      <P>
        Any passing on of personal data for legal purposes will only be done in compliance with laws
        of the country you reside in.
      </P>

      {/* ── Amendments ───────────────────────────────────── */}
      <H2 id="amendments">Amendments</H2>
      <P>
        We may amend this Privacy Policy from time to time. When we amend this Privacy Policy, we
        will update this page accordingly and require you to accept the amendments in order to be
        permitted to continue using our services.
      </P>

      {/* ── Contact Us ───────────────────────────────────── */}
      <H2 id="contact-us">Contact Us</H2>
      <P>If you have any questions about this Privacy Policy, you can contact us:</P>
      <UL>
        <li>By email: info@ctcminc.net</li>
        <li>By phone: 246-537-2826</li>
      </UL>
    </LegalPage>
  )
}
