import { Amplify } from "aws-amplify";

// amplify_outputs.json is generated by `npx ampx pipeline-deploy` (CI) or
// `npx ampx sandbox` (local). It is gitignored — never commit it.
// @ts-ignore - file is generated at deploy time, not present in source control
import outputs from "../../../../amplify_outputs.json";

Amplify.configure(outputs);

export { Amplify };
