import { Amplify } from "aws-amplify";

// amplify_outputs.json is generated by `npx ampx pipeline-deploy` (CI) or
// `npx ampx sandbox` (local). It is gitignored — never commit it.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated at deploy time; can't use @ts-expect-error because the
// CI stub makes the import resolve, causing "unused directive" errors locally
import outputs from "../../../../amplify_outputs.json";

Amplify.configure(outputs);

export { Amplify };
