import { Amplify } from "aws-amplify";
import outputs from "../../../../amplify_outputs.json";

// Configure Amplify with generated backend outputs.
// amplify_outputs.json is generated by `npx ampx generate outputs` after
// running `npx ampx sandbox` or a pipeline deploy.
Amplify.configure(outputs);

export { Amplify };
